### ISSUE TITLE
Notions are not connected with user

### ISSUE THREAD

**Issue by Vladislava05** [Vladislava05/TaskMaster#10]
when you try to create a notion with the form for this, it doesn't show created notion on the screen because the user is not defined automatically. It should be fixed.

**Comment by GusarevKirill** [comment]
ъУъ

**Comment by RGBsrs** [comment]
Maybe you can add screenshot with this bug?
Since according to the description it is a little unclear where the problem is.

**Comment by Vladislava05** [comment]
Try to create a note and you will see that it'll not appear on the page unless you choose a user in the form.

**Comment by RGBsrs** [comment]
Make pull request with fix

**Comment by RGBsrs** [comment]
🎄 С наступающим)

**Comment by Vladislava05** [comment]
@RGBsrs thanks for your work and... Merry Christmas!))
