### ISSUE TITLE
Make expired tasks

### ISSUE THREAD

**Issue by Vladislava05** [Vladislava05/TaskMaster#12]
1) Compare due_date and current date
2) If current date>due_date, task's icon becomes red.

**Comment by suryasis-hub** [comment]
Can I work on this issue ?

**Comment by Vladislava05** [comment]
Of course!

**Comment by Vladislava05** [comment]
@suryasis-hub hey there! How is it going? Do u have any problems?

**Comment by RGBsrs** [comment]
Nedd something more than in PR?
