### ISSUE TITLE
Add Date time field

### ISSUE THREAD

**Issue by Vladislava05** [Vladislava05/TaskMaster#2]
Add Date Time field to task-form's model

**Comment by RGBsrs** [comment]
You want add created time date filed to task in tasks list?
As at screenshot
![image](https://user-images.githubusercontent.com/50082968/142060487-dcc08b05-c1a2-4258-acea-fc33b5052c34.png)

**Comment by Vladislava05** [comment]
No, we want to add due date for task. For example, I have to do something on 24 November 2021.

**Comment by RGBsrs** [comment]
#5

**Comment by RGBsrs** [comment]
Could you tell me why my pull request not merged? 
Something wrong?

**Comment by Vladislava05** [comment]
Yeah, when user tries to sumbit, everything crashes.

**Comment by RGBsrs** [comment]
Maybe it is problems with db migration. 
I change field type. Can you check it now?
